# inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'Gemfile'
    - 'bin/*'

Bundler/OrderedGems:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

# Use $stderr instead of STDERR
Style/GlobalStdStream:
  Enabled: false

# Use warn instead of STDERR.puts
Style/StderrPuts:
  Enabled: false

# Need to re-enable all disabled cops in a source file
Lint/MissingCopEnableDirective:
  Enabled: false
