# Github action description file for Testing Rails apps with
# Rspec, SimpleCov and Rubocop

name: Ruby tests
on: [push, pull_request]

jobs:
  ruby-test:
    # Either 16.04, 18.04, 20.04 or latest
    # See https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest

    # services:
    #   # Docker services, use images from Docker hub
    #   # Using dockers health-check to wait for services to start,
    #   # see https://ryaneschinger.com/blog/using-docker-native-health-checks/
    #   postgres:
    #     image: postgres:12.5
    #     ports:
    #       - 5432:5432
    #     env:
    #       POSTGRES_USER: admin
    #       POSTGRES_PASSWORD: admin
    #     options: >-
    #       --health-cmd pg_isready
    #       --health-interval 5s
    #       --health-timeout 2s
    #       --health-retries 15

    steps:
      - name: Checkout code from Git
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7

      # - name: Install postgres client
      #   run: sudo apt-get install libpq-dev

      - name: Make sure bundler is installed
        run: gem install bundler

      - name: Output bundler version
        run: bundle --version

      - name: Install gem dependencies (bundle)
        run: bundle install --jobs 4 --retry 3

      - name: Run Rspec tests
        run: |
          RAILS_ENV=test bundle exec rspec --force-color

      - name: Run Rubocop Linting
        run: bundle exec rubocop --color
